import * as stylex from '@stylexjs/stylex';
import { colors, fonts, space } from './tokens.stylex';

const fadeUp = stylex.keyframes({
	from: {
		opacity: 0,
		transform: 'translateY(12px)',
	},
	to: {
		opacity: 1,
		transform: 'translateY(0)',
	},
});

export const layout = stylex.create({
	shell: {
		minHeight: '100dvh',
		display: 'flex',
		flexDirection: 'column',
		backgroundColor: colors.bg,
		color: colors.fg,
	},
	main: {
		flex: '1',
		width: '100%',
	},
	container: {
		width: '100%',
		maxWidth: 'var(--content-max)',
		marginInline: 'auto',
		paddingInline: 'var(--frame-inner-pad, var(--space-page))',
	},
	section: {
		paddingBlock: `clamp(3.5rem, 10vw, ${space['4xl']})`,
	},
	sectionHead: {
		display: 'block',
		width: 'fit-content',
		maxWidth: '100%',
		margin: `0 0 ${space.lg}`,
	},
	sectionTitle: {
		fontFamily: fonts.display,
		fontSize: 'clamp(1.75rem, 3.5vw, 2.5rem)',
		fontWeight: 400,
		lineHeight: 1.15,
		letterSpacing: '-0.02em',
		textWrap: 'balance',
		margin: 0,
		color: colors.fg,
	},
	lede: {
		fontFamily: fonts.body,
		fontSize: '1.0625rem',
		lineHeight: 1.6,
		color: colors.muted,
		maxWidth: '36rem',
		textWrap: 'pretty',
		margin: 0,
	},
});

export const hero = stylex.create({
	root: {
		position: 'relative',
		isolation: 'isolate',
	},
	cover: {
		position: 'relative',
		width: '100%',
		height: 'var(--hero-cover-height)',
		overflow: 'hidden',
		backgroundColor: colors.bg,
	},
	coverPhoto: {
		position: 'absolute',
		inset: 0,
		width: '100%',
		height: '100%',
		maxWidth: 'none',
		objectFit: 'cover',
		objectPosition: 'center 42%',
		maskImage: 'var(--hero-cover-mask)',
		WebkitMaskImage: 'var(--hero-cover-mask)',
		maskSize: '100% 100%',
		maskRepeat: 'no-repeat',
	},
	atmosphere: {
		position: 'absolute',
		inset: 0,
		pointerEvents: 'none',
		backgroundColor: 'var(--color-hero-atmosphere)',
	},
	grain: {
		position: 'absolute',
		inset: 0,
		opacity: 'var(--hero-cover-grain-opacity)',
		pointerEvents: 'none',
		backgroundImage: `url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.85' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='0.55'/%3E%3C/svg%3E")`,
		mixBlendMode: 'soft-light',
	},
	scrim: {
		position: 'absolute',
		inset: 0,
		pointerEvents: 'none',
		backgroundImage: 'var(--hero-cover-scrim)',
	},
	inner: {
		width: '100%',
		maxWidth: 'var(--content-max)',
		marginInline: 'auto',
		paddingInline: space.page,
		paddingBottom: space['2xl'],
	},
	identity: {
		display: 'flex',
		flexWrap: 'wrap',
		alignItems: 'center',
		columnGap: space.xl,
		rowGap: space.lg,
		'@media (min-width: 36rem)': {
			flexWrap: 'nowrap',
			alignItems: 'flex-start',
			marginTop: 'calc(var(--hero-avatar-size) * -0.42)',
		},
	},
	portraitWrap: {
		display: 'block',
		width: 'var(--hero-avatar-size)',
		height: 'var(--hero-avatar-size)',
		aspectRatio: '1 / 1',
		flexShrink: 0,
		marginTop: 'calc(var(--hero-avatar-size) * -0.5)',
		padding: '4px',
		borderRadius: '9999px',
		overflow: 'hidden',
		boxSizing: 'border-box',
		backgroundColor: colors.bg,
		boxShadow: `0 8px 24px color-mix(in oklab, ${colors.shadow} 16%, transparent)`,
		'@media (min-width: 36rem)': {
			marginTop: 0,
		},
		'@media (prefers-reduced-motion: no-preference)': {
			animationName: fadeUp,
			animationDuration: '700ms',
			animationTimingFunction: 'cubic-bezier(0.2, 0, 0, 1)',
			animationFillMode: 'both',
		},
	},
	portrait: {
		display: 'block',
		width: '100%',
		height: '100%',
		maxWidth: 'none',
		aspectRatio: '1 / 1',
		borderRadius: '9999px',
		objectFit: 'cover',
		objectPosition: 'center top',
		outlineWidth: '1px',
		outlineStyle: 'solid',
		outlineColor: colors.imageOutline,
		outlineOffset: '-1px',
	},
	copy: {
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'flex-start',
		flex: '1 1 18rem',
		gap: space.sm,
		minWidth: 0,
		maxWidth: '40rem',
		'@media (min-width: 36rem)': {
			paddingTop: '0.5rem',
		},
	},
	brand: {
		fontFamily: fonts.display,
		fontSize: 'clamp(2.125rem, 5vw, 3.25rem)',
		fontWeight: 400,
		lineHeight: 1.1,
		letterSpacing: '-0.03em',
		textWrap: 'balance',
		margin: 0,
		color: colors.fg,
	},
	headline: {
		fontFamily: fonts.body,
		fontSize: 'clamp(1.125rem, 2.2vw, 1.375rem)',
		fontWeight: 500,
		lineHeight: 1.35,
		letterSpacing: '-0.015em',
		textWrap: 'balance',
		margin: 0,
		color: colors.fg,
		'@media (prefers-reduced-motion: no-preference)': {
			animationName: fadeUp,
			animationDuration: '700ms',
			animationDelay: '240ms',
			animationTimingFunction: 'cubic-bezier(0.2, 0, 0, 1)',
			animationFillMode: 'both',
		},
	},
	support: {
		fontFamily: fonts.body,
		fontSize: '1rem',
		lineHeight: 1.6,
		color: colors.muted,
		maxWidth: '34rem',
		textWrap: 'pretty',
		margin: 0,
		'@media (prefers-reduced-motion: no-preference)': {
			animationName: fadeUp,
			animationDuration: '700ms',
			animationDelay: '320ms',
			animationTimingFunction: 'cubic-bezier(0.2, 0, 0, 1)',
			animationFillMode: 'both',
		},
	},
	ctas: {
		display: 'flex',
		flexWrap: 'wrap',
		alignItems: 'center',
		gap: space.md,
		marginTop: space.md,
		'@media (prefers-reduced-motion: no-preference)': {
			animationName: fadeUp,
			animationDuration: '700ms',
			animationDelay: '400ms',
			animationTimingFunction: 'cubic-bezier(0.2, 0, 0, 1)',
			animationFillMode: 'both',
		},
	},
});

export const button = stylex.create({
	base: {
		display: 'inline-flex',
		alignItems: 'center',
		justifyContent: 'center',
		gap: space.sm,
		height: '2.875rem',
		paddingInline: '1.25rem',
		borderRadius: '10px',
		fontFamily: fonts.body,
		fontSize: '0.9375rem',
		fontWeight: 600,
		letterSpacing: '-0.01em',
		borderWidth: 0,
		borderStyle: 'none',
		cursor: 'pointer',
		textDecoration: 'none',
		transitionProperty: 'background-color, color, transform',
		transitionDuration: '160ms',
		transitionTimingFunction: 'cubic-bezier(0.2, 0, 0, 1)',
		':active': {
			transform: 'scale(0.96)',
		},
	},
	primary: {
		backgroundColor: colors.primary,
		color: colors.primaryFg,
		':hover': {
			backgroundColor: colors.primaryHover,
			color: colors.primaryFg,
		},
		':focus-visible': {
			outlineColor: colors.ring,
			color: colors.primaryFg,
		},
	},
	ghost: {
		backgroundColor: colors.secondary,
		color: colors.fg,
		':hover': {
			backgroundColor: colors.accent,
			color: colors.accentFg,
		},
	},
});

export const about = stylex.create({
	grid: {
		display: 'grid',
		gap: space['2xl'],
		'@media (min-width: 768px)': {
			gridTemplateColumns: 'minmax(0, 0.9fr) minmax(0, 1.1fr)',
			alignItems: 'start',
		},
	},
	meta: {
		display: 'flex',
		flexDirection: 'column',
		gap: space.md,
		fontFamily: fonts.body,
		fontSize: '0.9375rem',
		color: colors.muted,
	},
	metaRow: {
		display: 'flex',
		gap: space.sm,
		alignItems: 'center',
	},
	metaLabel: {
		fontSize: '0.75rem',
		fontWeight: 500,
		letterSpacing: '0.06em',
		textTransform: 'uppercase',
		color: colors.muted,
		minWidth: '5.5rem',
	},
	body: {
		fontFamily: fonts.body,
		fontSize: '1.0625rem',
		lineHeight: 1.65,
		color: colors.fg,
		maxWidth: '38rem',
		textWrap: 'pretty',
		margin: 0,
	},
	experience: {
		marginTop: space['2xl'],
		paddingTop: space.xl,
		boxShadow: `inset 0 1px 0 ${colors.borderSubtle}`,
	},
	expRole: {
		fontFamily: fonts.body,
		fontSize: '1rem',
		fontWeight: 600,
		letterSpacing: '-0.01em',
		margin: 0,
		color: colors.fg,
	},
	expMeta: {
		fontFamily: fonts.body,
		fontSize: '0.875rem',
		color: colors.muted,
		margin: `${space.xs} 0 ${space.md}`,
	},
	expList: {
		margin: 0,
		paddingInlineStart: '1.1rem',
		display: 'flex',
		flexDirection: 'column',
		gap: space.sm,
	},
	expItem: {
		fontFamily: fonts.body,
		fontSize: '0.9375rem',
		lineHeight: 1.55,
		color: colors.fg,
		textWrap: 'pretty',
	},
});

export const skills = stylex.create({
	groups: {
		display: 'flex',
		flexDirection: 'column',
		gap: space.xl,
		marginTop: space.xl,
	},
	group: {
		display: 'flex',
		flexDirection: 'column',
		gap: space.sm,
	},
	label: {
		fontFamily: fonts.body,
		fontSize: '0.6875rem',
		fontWeight: 500,
		letterSpacing: '0.06em',
		textTransform: 'uppercase',
		color: colors.muted,
		margin: 0,
	},
	list: {
		display: 'flex',
		flexWrap: 'wrap',
		gap: '0.4rem',
		padding: 0,
		listStyle: 'none',
		margin: 0,
		'@media (min-width: 48rem)': {
			gap: '0.55rem',
		},
	},
	chip: {
		display: 'inline-flex',
		alignItems: 'center',
		gap: '0.4rem',
		fontFamily: fonts.body,
		fontSize: '0.8125rem',
		fontWeight: 500,
		letterSpacing: '-0.01em',
		lineHeight: 1.2,
		color: colors.fg,
		backgroundColor: colors.secondary,
		paddingBlock: '0.35rem',
		paddingInline: '0.65rem',
		borderRadius: '6px',
		transitionProperty: 'background-color, color',
		transitionDuration: '140ms',
		transitionTimingFunction: 'cubic-bezier(0.2, 0, 0, 1)',
		':hover': {
			backgroundColor: colors.accent,
			color: colors.accentFg,
		},
		'@media (min-width: 48rem)': {
			gap: '0.5rem',
			fontSize: '0.9375rem',
			paddingBlock: '0.5rem',
			paddingInline: '0.85rem',
			borderRadius: '8px',
		},
	},
	mark: {
		display: 'inline-flex',
		alignItems: 'center',
		justifyContent: 'center',
		width: '1rem',
		height: '1rem',
		flexShrink: 0,
		color: 'inherit',
		opacity: 0.85,
		'@media (min-width: 48rem)': {
			width: '1.125rem',
			height: '1.125rem',
		},
	},
});

export const projects = stylex.create({
	list: {
		display: 'flex',
		flexDirection: 'column',
		margin: `${space['2xl']} 0 0`,
		padding: 0,
		listStyle: 'none',
		gap: 0,
	},
	item: {
		paddingBlock: space.xl,
		boxShadow: `inset 0 -1px 0 ${colors.borderSubtle}`,
		':last-child': {
			boxShadow: 'none',
		},
	},
	body: {
		display: 'grid',
		gap: space.md,
		'@media (min-width: 720px)': {
			gridTemplateColumns: 'minmax(0, 1fr) minmax(0, 1.15fr)',
			gap: space['2xl'],
			alignItems: 'start',
		},
	},
	heading: {
		display: 'flex',
		flexDirection: 'column',
		gap: space.sm,
	},
	name: {
		fontFamily: fonts.body,
		fontSize: 'clamp(1.0625rem, 2vw, 1.1875rem)',
		fontWeight: 600,
		letterSpacing: '-0.015em',
		lineHeight: 1.3,
		margin: 0,
		color: colors.fg,
		textWrap: 'balance',
	},
	stack: {
		fontFamily: fonts.body,
		fontSize: '0.8125rem',
		fontWeight: 500,
		lineHeight: 1.45,
		color: colors.accentText,
		margin: 0,
		textWrap: 'pretty',
	},
	bullets: {
		margin: 0,
		paddingInlineStart: '1.1rem',
		display: 'flex',
		flexDirection: 'column',
		gap: '0.45rem',
	},
	bullet: {
		fontFamily: fonts.body,
		fontSize: '0.9375rem',
		lineHeight: 1.5,
		color: colors.muted,
		textWrap: 'pretty',
	},
});

export const contact = stylex.create({
	panel: {
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'flex-start',
		gap: space.xl,
		marginTop: space['2xl'],
		paddingTop: space['2xl'],
		boxShadow: `inset 0 1px 0 ${colors.borderSubtle}`,
	},
	actions: {
		display: 'flex',
		flexWrap: 'wrap',
		alignItems: 'center',
		gap: space.md,
	},
});

export const footer = stylex.create({
	root: {
		paddingBlock: `clamp(2rem, 5vw, ${space['3xl']})`,
		marginTop: 'auto',
	},
	inner: {
		display: 'flex',
		flexWrap: 'wrap',
		justifyContent: 'space-between',
		alignItems: 'baseline',
		gap: space.md,
		maxWidth: 'var(--content-max)',
		marginInline: 'auto',
		paddingInline: {
			default: `calc(${space.page} + var(--space-inner))`,
			'@media (min-width: 72rem)': space.page,
		},
		fontFamily: fonts.body,
		fontSize: '0.8125rem',
		color: colors.muted,
		paddingTop: space.xl,
	},
	mark: {
		fontFamily: fonts.display,
		fontStyle: 'italic',
		fontSize: '1rem',
		letterSpacing: '-0.02em',
		color: colors.fg,
	},
});
